### ISSUE TITLE
Also download messages?

### ISSUE THREAD

**Issue by chemxboy** [pdumoulin/brightwheel-downloader#1]
This project works great! Have you been able to find a way to download the messages as well? It would be nice if they were added to the db too. I found the endpoint students/{}/messages but can't seem to make it get to a second page as you do with the activities.

**Comment by pdumoulin** [comment]
Hello! I'm glad you're enjoying the project. I haven't had a need to download messages, but I took a quick look at how the web UI at https://schools.mybrightwheel.com/messages/messages functions, and may be able to point you in the right direction if you wanted to add that feature.

Here's a flow that I think might work...
1. Request is made to https://schools.mybrightwheel.com/api/v1/users/me (in the python script this is already done when the client initializes and your user ID is saved as `user_id` on the client object)
3. Request is made to https://schools.mybrightwheel.com/api/v2/guardians/{user_id}/message_threads - a list of message threads is returned, each one has `object_id` that you can use in the next step...
4. Request is made to https://schools.mybrightwheel.com/api/v2/guardians/{user_id}/message_threads/{message_thread_id}/messages?page_limit=25 - the response includes messages. Pagination works differently than the activity feed, when going to a new page, the URL parameter `starting_after` is appended. It appears to be an ID of a specific message and can be used to iterate over pages of messages.
